### PR TITLE
Add support for overriding variables in device-specific context

### PR DESCRIPTION
**Pull request by xorrkaz**
Provide an option that allows for device-specific variables to override base variables.  By default, this option is False to retain existing functionality.

### CODE REVIEW

**Review by wkumari — APPROVED** [review]
Awesome, thank you, and apologies for the delay in reviewing.

I've actually done a large amount of hacking on this too, but (stupidly) I've been doing it in a private repo; I need to remember to backport it here. 

Turns out the whole submodule idea of mine was stoopid - if I ever suggest that again, please slap me...

**Comment by xorrkaz** [comment]
Why not push this to PyPi?  This way we can `pip install` it and wouldn't have to deal with submodules.

**Comment by wkumari** [comment]
That's definitely an idea, and let's discuss it some more.


Initially it doesn't really feel "right" to me, but I'm not entirely sure why. I think that it is a combination of:
1: it doesn't really feel sufficiently baked yet.
2: the Python bits are only [build.py](http://build.py/), and the vast majority of the "code" is Jinja templates.

`cloc` speaketh thusly:
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jinja Template                  35              1              1           1058
Markdown                         2             99              0            317
Python                           1             72            103            233
YAML                             2             13             13            135
TOML                             1              0              0              2
Text                             1              0              0              2
-------------------------------------------------------------------------------
SUM:                            42            185            117           1747
-------------------------------------------------------------------------------
```

3: I (embarrassingly) have 3 or 4 different versions of this project -- I've tweaked it slightly to deal with a network which I help run which has many many VLANs (and so it supports an inverse "VLAN->Interface" mapping file), and futzeled with it in another project to support pulling many of the stats from NetBox. If we had this is something like PyPi it would be hard to have different versions of this.... That is almost certainly a feature, not a bug though.... 

What I think would make more sense (and I'm not offering to do the work, yet :-)) is to first fix build.py so that it doesn't make the current, fairly awful assumptions about where the templates life related to the binary. I know that there are issues with this around https://github.com/wkumari/router-config-builder/blob/aa5570a2aba916941d5a79fdfb5e0a8dad81f391/build.py#L357, but I have a horrible feeling that there are more... 
This also does not fix my number 3 above, but, again, that's probably a feature, not a big... 

PyPi might be a grand idea, but I'm not convinced yet...

**Comment by xorrkaz** [comment]
I've put "local" tools up in PyPi because it's easy, and it makes my user of them easier.  I do think this needs some setup.py-like wrapping, and I agree with you on the template location bit.  I'm happy to sign up for that work to make this packageable.

**Comment by wkumari** [comment]
Oooh, yes please! 
Github comments are (largely) permanent, so we have archival proof of your offer :-)

**Pull request merged**
